networks:
  frontend:
    name: frontend
  backend:
    name: backend

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_VERSION}
    container_name: nginx-proxy
    labels:
      - com.github.nginx-proxy.nginx=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - frontend
      - backend
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${ACME_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - frontend
    restart: always

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    # ports: - "9000:9000" # Comentado porque entramos vía Proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=portainer.${MAIN_DOMAIN}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.${MAIN_DOMAIN}
    networks:
      - frontend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    environment:
      - VIRTUAL_HOST=prometheus.${MAIN_DOMAIN}
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=prometheus.${MAIN_DOMAIN}
    networks:
      - backend
      - frontend
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=grafana.${MAIN_DOMAIN}
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.${MAIN_DOMAIN}
    networks:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  portainer_data:
  grafana_data:
  prometheus_data:
  certs:
  vhost:
  html:
  acme:
